fix: use nodejs for release build

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -16,27 +16,28 @@ jobs:
               with:
                   fetch-depth: 0
 
-            - name: Set up Bun
-              uses: oven-sh/setup-bun@v1
+            - name: Set up Node.js
+              uses: actions/setup-node@v4
               with:
-                  bun-version: "latest"
+                  node-version: 20
 
             - name: Install dependencies
-              run: bun install
+              run: npm install
 
             - name: Build static export
               run: |
-                  bun run build-ignore-error
+                  npm run build-ignore-error
 
             - name: Compress dist folder
-              run: zip -r dist.zip dist
+              run: |
+                  if [ -d "dist" ]; then
+                    zip -r dist.zip dist
+                  else
+                    echo "dist folder not found!"
+                    exit 1
+                  fi
 
             - name: Release
               uses: softprops/action-gh-release@v2
               with:
                   files: dist.zip
-
-            - name: Changelog
-              run: bun x changelogithub
-              env:
-                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
